
import React, { useState } from 'react';
import { AnalysisResult } from '../types';
import { AlertTriangle, Code, CheckCircle, Lightbulb, Box, Activity, Copy, Download, Check, ShieldAlert, Zap } from 'lucide-react';

interface AnalysisCardProps {
  result: AnalysisResult;
  isHistorical?: boolean;
}

export const AnalysisCard: React.FC<AnalysisCardProps> = ({ result, isHistorical = false }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyCode = () => {
    if (result.codeSnippet) {
      navigator.clipboard.writeText(result.codeSnippet);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    const content = `
ETL ERROR ANALYSIS REPORT
-------------------------
Tool: ${result.tool}
Date: ${new Date(result.timestamp).toLocaleString()}
Error Type: ${result.errorType}
Severity: ${result.severity}
Component: ${result.component}
Job Name: ${result.jobName || 'Unknown'}

ROOT CAUSE:
${result.cause}

RECOMMENDED FIX:
${result.fix}

OPTIMIZED SOLUTION:
${result.optimizedSolution}

CODE SNIPPET:
${result.codeSnippet || 'N/A'}

Generated by ETL Fixer AI
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Error_Report_${result.tool}_${result.id.slice(0, 8)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'Critical': return 'bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 border-red-200 dark:border-red-900/50';
      case 'High': return 'bg-orange-100 dark:bg-orange-900/30 text-orange-800 dark:text-orange-300 border-orange-200 dark:border-orange-900/50';
      case 'Medium': return 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-800 dark:text-yellow-300 border-yellow-200 dark:border-yellow-900/50';
      case 'Low': return 'bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300 border-blue-200 dark:border-blue-900/50';
      default: return 'bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700';
    }
  };

  return (
    <div className={`bg-white dark:bg-slate-900 rounded-xl shadow-lg border overflow-hidden transition-all duration-500 animate-fade-in ${isHistorical ? 'border-amber-300 ring-2 ring-amber-100 dark:border-amber-600 dark:ring-amber-900/30' : 'border-gray-200 dark:border-slate-700'}`}>
      {/* Header Bar */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 dark:border-slate-800 bg-gray-50/50 dark:bg-slate-800/50">
        <div className="flex items-center gap-3">
          <span className={`px-3 py-1 rounded-full text-xs font-bold border uppercase tracking-wide flex items-center gap-1.5 ${getSeverityColor(result.severity)}`}>
            <ShieldAlert className="w-3.5 h-3.5" />
            {result.severity} Severity
          </span>
          {result.jobName && (
             <span className="text-xs font-medium text-gray-500 dark:text-gray-400 bg-white dark:bg-slate-800 px-2 py-1 rounded border border-gray-200 dark:border-slate-700 shadow-sm">
                Job: {result.jobName}
             </span>
          )}
        </div>
        <div className="flex items-center gap-4 text-xs font-medium text-gray-500 dark:text-gray-400">
             <div className="flex items-center gap-1.5" title="AI Confidence Score">
                <Zap className={`w-3.5 h-3.5 ${result.confidenceScore > 80 ? 'text-green-500' : 'text-yellow-500'}`} />
                {result.confidenceScore}% Confidence
             </div>
             <button 
                onClick={handleDownload}
                className="flex items-center gap-1.5 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
             >
                <Download className="w-3.5 h-3.5" /> Export
             </button>
        </div>
      </div>

      {isHistorical && (
        <div className="bg-amber-50 dark:bg-amber-900/20 px-6 py-2 border-b border-amber-200 dark:border-amber-900/30 flex items-center text-amber-700 dark:text-amber-400 text-sm font-medium">
          <AlertTriangle className="w-4 h-4 mr-2" />
          Recurring Error Detected: This issue has been encountered before.
        </div>
      )}
      
      <div className="p-6">
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            {result.errorType}
          </h2>
          <p className="text-gray-500 dark:text-gray-400 mt-2 flex items-center gap-2">
             <Box className="w-4 h-4" /> Component: <span className="font-mono font-medium text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/30 px-2 py-0.5 rounded border border-indigo-100 dark:border-indigo-900/50">{result.component}</span>
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div className="bg-white dark:bg-slate-800 p-5 rounded-lg border border-gray-200 dark:border-slate-700 shadow-sm">
            <h3 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 flex items-center gap-2">
              <Activity className="w-4 h-4" /> Root Cause
            </h3>
            <p className="text-gray-800 dark:text-gray-200 text-sm leading-relaxed">{result.cause}</p>
             {result.lineOfCode && (
                 <div className="mt-4 inline-block text-xs font-mono text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-slate-700 px-2 py-1 rounded">
                     Line/Loc: {result.lineOfCode}
                 </div>
             )}
          </div>

          <div className="bg-green-50/50 dark:bg-green-900/10 p-5 rounded-lg border border-green-100 dark:border-green-900/30 shadow-sm">
            <h3 className="text-sm font-semibold text-green-700 dark:text-green-400 uppercase tracking-wider mb-3 flex items-center gap-2">
              <CheckCircle className="w-4 h-4" /> Recommended Fix
            </h3>
            <p className="text-gray-800 dark:text-gray-200 text-sm leading-relaxed">{result.fix}</p>
          </div>
        </div>

        {result.codeSnippet && (
            <div className="mb-6 group relative">
                <div className="flex items-center justify-between mb-2">
                    <h3 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider flex items-center gap-2">
                        <Code className="w-4 h-4" /> Code Suggestion
                    </h3>
                    <button 
                        onClick={handleCopyCode}
                        className="text-xs flex items-center gap-1 text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 font-medium transition-colors"
                    >
                        {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        {copied ? 'Copied!' : 'Copy Snippet'}
                    </button>
                </div>
                <div className="bg-slate-900 dark:bg-black rounded-lg p-4 overflow-x-auto border border-slate-800 dark:border-slate-800 shadow-inner relative">
                    <pre className="text-indigo-300 font-mono text-sm leading-6">{result.codeSnippet}</pre>
                </div>
            </div>
        )}

        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border-l-4 border-blue-500 p-5 rounded-r-lg">
             <h3 className="text-sm font-semibold text-blue-700 dark:text-blue-400 uppercase tracking-wider mb-2 flex items-center gap-2">
                <Lightbulb className="w-4 h-4" /> Optimization Tip
             </h3>
             <p className="text-blue-900 dark:text-blue-200 text-sm leading-relaxed">{result.optimizedSolution}</p>
        </div>
      </div>
    </div>
  );
};
